# Generated by Django 4.1.4 on 2023-01-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='user_code',
            field=models.CharField(default='8737', max_length=4),
        ),
    ]
