# Generated by Django 4.1.4 on 2023-01-03 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_code_user_status_alter_code_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='code',
            name='user_code',
            field=models.CharField(default='1783', max_length=4),
        ),
    ]
