# Generated by Django 4.1.4 on 2023-01-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_post_current_user_alter_author_authoruser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='user_code',
            field=models.CharField(default='9403', max_length=4),
        ),
    ]
