# Generated by Django 4.1.4 on 2023-01-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_code_user_code_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='user',
            new_name='authorNewsletter',
        ),
        migrations.AlterField(
            model_name='code',
            name='user_code',
            field=models.CharField(default='2296', max_length=4),
        ),
    ]
