# Generated by Django 4.1.4 on 2023-01-08 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0013_alter_code_user_code_alter_newsletter_usernewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='user_code',
            field=models.CharField(default='4045', max_length=4),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='userNewsletter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
