# Generated by Django 4.1.4 on 2023-01-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_code_user_code_alter_newsletter_usernewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='user_code',
            field=models.CharField(default='8588', max_length=4),
        ),
    ]
