# Generated by Django 4.1.4 on 2023-01-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_code_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='user_code',
            field=models.CharField(default='9850', max_length=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_news',
            field=models.CharField(choices=[('Танки', 'Танки'), ('Хилы', 'Хилы'), ('DD', 'ДД'), ('Merchants', 'Торговцы'), ('Guildmasters', 'Гилдмастеры'), ('Questgivers', 'Квестгиверы'), ('Blacksmiths', 'Кузнецы'), ('Leatherworkers', 'Кожевники'), ('Potions Masters', 'Зельевары'), ('Spellmasters', 'Мастера заклинаний')], default='Tanks', max_length=64),
        ),
    ]
